### ISSUE TITLE
Is deployment in the 2.1.11 release broken?

### ISSUE THREAD

**Issue by hekonsek** [fabric8io/jube#300]
Hi,

I'm trying to deploy quickstarts into jube 2.1.11. For example java/camel-spring. I get the following error on the Maven plugin side:

```
mvn -Dfabric8.recreate=true clean install fabric8:json fabric8:apply
...
java.lang.NullPointerException
	at io.fabric8.kubernetes.api.KubernetesHelper.toJson(KubernetesHelper.java:361)
	at io.fabric8.kubernetes.api.Controller.logGeneratedEntity(Controller.java:354)
	at io.fabric8.kubernetes.api.Controller.doCreateReplicationController(Controller.java:657)
	at io.fabric8.kubernetes.api.Controller.applyReplicationController(Controller.java:619)
	at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:207)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:196)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:191)
	at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:152)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

...and this on the Jube server side...

```
2015-06-10 22:17:01,728 [ool-25-thread-1] ERROR ApiMasterService               - Failed to create container quickstart-java-camel-spring-1. java.lang.NullPointerException
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:464)[:1.8.0_05]
	at io.fabric8.kubernetes.api.KubernetesHelper.getCurrentContainers(KubernetesHelper.java:966)[kubernetes-api-2.1.11.jar:2.1.11]
	at io.fabric8.jube.local.NodeHelper.createMissingContainers(NodeHelper.java:189)[node-2.1.11.jar:2.1.11]
	at io.fabric8.jube.apimaster.ApiMasterService$2$1.run(ApiMasterService.java:551)[node-2.1.11.jar:2.1.11]
	at io.fabric8.jube.local.NodeHelper.excludeFromProcessMonitor(NodeHelper.java:626)[node-2.1.11.jar:2.1.11]
	at io.fabric8.jube.apimaster.ApiMasterService$2.run(ApiMasterService.java:558)[node-2.1.11.jar:2.1.11]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_05]
2015-06-10 22:17:05,006 [Timer-10       ] ERROR NIOServerCnxnFactory           - Thread Thread[Timer-10,5,main] died
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:464)[:1.8.0_05]
	at io.fabric8.kubernetes.api.KubernetesHelper.getCurrentContainers(KubernetesHelper.java:966)[kubernetes-api-2.1.11.jar:2.1.11]
	at io.fabric8.kubernetes.api.KubernetesHelper.getCurrentContainers(KubernetesHelper.java:951)[kubernetes-api-2.1.11.jar:2.1.11]
	at io.fabric8.jube.local.LocalKubernetesModel.getPodRunningContainers(LocalKubernetesModel.java:165)[node-2.1.11.jar:2.1.11]
	at io.fabric8.jube.apimaster.ApiMasterKubernetesModel.getPodRunningContainers(ApiMasterKubernetesModel.java:224)[node-2.1.11.jar:2.1.11]
	at io.fabric8.jube.local.ProcessMonitor.processMonitor(ProcessMonitor.java:77)[node-2.1.11.jar:2.1.11]
	at io.fabric8.jube.local.ProcessMonitor$1.run(ProcessMonitor.java:68)[node-2.1.11.jar:2.1.11]
	at java.util.TimerThread.mainLoop(Timer.java:555)[:1.8.0_05]
	at java.util.TimerThread.run(Timer.java:505)[:1.8.0_05]
```

It looks like a major regression to me.

**Comment by davsclaus** [comment]
Yes and btw you use fabric8:deploy for jube, not apply.

**Comment by Tires** [comment]
How can I use Jube, if I can't deploy to it?

**Comment by davsclaus** [comment]
jube does not work currently. We have too much other stuff on our plate currently to fix and implement jube.

I suggest to try the real thing such as the vagrant image

**Comment by Tires** [comment]
What is the last working version?

I would wonder, if theren't a lot who can't have Linux running. Especially for mixed systems on a trasition to cloud, this would be beneficial.

**Comment by davsclaus** [comment]
Ah that is a while back, That would be the 2.0.x release something.
